variable "name" {}
variable "location" {}
variable "resource_group_name" {}
variable "storage_image_reference" {}
variable "subnet_id" {}
variable "zone_name" {}
variable "network_security_group_id" {}
variable "dns_resource_group_name" {}
variable "token" {}
variable "type" {}
variable "vm_size" {}
variable "port" {}
variable "subnet_cidr" {}
variable "disk_encryption_set_id" {}